yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error_500'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/about/models.py
# from django.db import models

# Create your models here.

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="container py-5">
<hr>
<h1>Привет!</h1>
<h3>Меня зовут Саша Петров</h3>
<hr>
<p>
  Я учусь в 51 когорте курса "Python-разработчик" Яндекс.Пракутима.
</p>
<p>
  Я бы с удовольствием поэкспериментировал бы с Bootstrap'ом, ссылками и картинками, но у меня осталось ультра мало времени для закрытия четвертого спринта.
  Поэтому я представлю, что разместил здесь подробную дорожную карту своего успешного пути к становлению властелином кода и фреймворков,
  возможно научился по дороге любить раф, а в мои потребности стала входить давилка для имбиря на кухне в офисе 
  (про давилку - реальный случай из одной крупной российской IT-компании) 
</p>
<p>
  Поэтому я просто продемонстрирую, что я умею (или не умею) вставлять ссылки, картинки и немножко в Bootstrap и html (если вдруг это важно для ревью финального проекта).
</p>
<hr>
<h1>
  Итак, демонстрирую
</h1>
<hr>
<p>
  Вот можно добавалять ссылки - добавлю здесь ссылки на github (не уверен, что репозитории у меня публичные, но хотя бы пусть будут ссылки на них):
  <ul>
    <li>
      <a href="https://github.com/AlexanderPAI/character_creation_module.git" class="link-success">
        Вот это ссылка на репозиторий из обновленного второго спринта (очень захотелось пройти заново после обновления). 
        Ссылка должна быть зеленой (опять "Привет, Bootstap")
      </a>
    </li>
    <li>
      <a href="https://github.com/AlexanderPAI/yatube_project.git" class="link-danger">
        А вот это ссылка на репозиторий, собственно, этого проекта, по состоянию на четвертый спринт. 
        Она красная, потому что у меня жестко подгорел пердак от того, что в этом спринте очень мало 
        инфы о декораторах и про *args и *kwargs (пришлось очень долго разбираться самому, поэтому и 
        опаздываю с четвертым спринтом)
      </a>
    </li>
    <li>
      Ну и ссылки, разумеется в маркированном списке, чтобы показать, что я знаю теги маркированного списка в HTML (Очуметь достижение=))
    </li>
  </ul>
</p>
<hr>
<p>
  А вот так можно вставлять адаптивные картинки благодаря Bootstrap'у. Она будет ратягиваться по ширине страницы.
  С уважением, Ваш автор этого проекта:
  <img src="https://connery.dk/image/box/2136195/3920/50000.jpg?oversize=1" class="img-fluid" alt="Responsive image">
  <table>

  </table>
</p>
<p>
  А если ты все-таки долистал до конца страницы и видишь это - желаю тебе терперния со студентами, 
  Ревьюер, Наставник или Куратор курса (кто бы не смотрел на ЭТО)!
</p>
</div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="container py-5">
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        Немножко Bootstrap
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Ну в общем почему здесь так мало сделано? Все объяснено на странице <a href="{% url 'about:author' %}">об авторе</a> </p>
    <img src="https://yt3.ggpht.com/ytc/AKedOLQXdVw0XBQLRAySp2kBKAfQVy7M09baq4bjQy7v=s900-c-k-c0x00ffffff-no-rj" class="img-fluid" alt="Responsive image">
  </article>
</div>
</div>
{% endblock %}